version: '3'
services:
  django:
    build:
      context: ./django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - mqtt
    env_file:
      - .env
    volumes:
      - ./django_app:/app
    command: bash -c "python manage.py collectstatic --noinput &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mqtt:
    build:
      context: ./Mos/
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./Mos/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./Mos/data/:/mosquitto/data/